version: "2.18.1"

services:
  backend:
    build:
      context: .
    ports:
      - 8090:8090
    volumes:
      - data_zyfra_blog:/data
    command: bash -c "python manage.py runserver 0.0.0.0:8090"
volumes:
  data_zyfra_blog: